POST http://localhost:3333/videos  
Content-type: application/json

{
    "title":"Video 02",
    "description":"o video 02 da trem!",
    "duration": 180
}

###

GET http://localhost:3333/videos

###

PUT http://localhost:3333/videos/8d20b448-b705-4570-acb4-0473a5c77b1a
Content-Type: application/json

{
    "title":"Agora é video 02",
    "description":"o video 02 da parada!",
    "duration": 108
}

###

DELETE http://localhost:3333/videos/8d20b448-b705-4570-acb4-0473a5c77b1a
